require 'league_of_legends/request/all'
require 'league_of_legends/request/base'
require 'league_of_legends/request/champion'
require 'league_of_legends/request/game/by_summoner/recent'
require 'league_of_legends/request/league/challenger'
require 'league_of_legends/request/mapper'
require 'league_of_legends/request/stats/by_summoner/ranked'
require 'league_of_legends/request/stats/by_summoner/summary'